import { type NextPage } from "next";
import Head from "next/head";
import { Outfit } from "@next/font/google";

import { api } from "../utils/api";
import Message from "../components/message";
import Highlight from "../components/highlight";

/** Highlight image */
import ladderImage from "../../public/ladder.jpeg";
import dmb from "../../public/dmb.jpg";
import elizabethtown from "../../public/elizabethtown-hallway.jpg";
import computer from "../../public/computer.jpeg";

const font = Outfit({
  subsets: ["latin"],
});

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const text = hello.data ? hello.data.greeting : "Loading tRPC query...";

  return (
    <>
      <Head>
        <title>Prakash Raman - Website</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={[font.className].join(" ")}>
        {/* Main Body */}
        <div className="relative">
          {/* Left Panel */}
          <div className="mr-[300px] pl-[80px]">
            {/* Hero */}
            <section className="flex h-screen items-center border-b border-line">
              <div className="relative flex h-full flex-col justify-center">
                <h1 className="mb-7 text-left text-7xl font-semibold">
                  Prakash Raman
                </h1>
                <h3 className="max-w-2xl text-2xl font-extralight text-gray-500">
                  As the head of Application Development at Sentiance, my role
                  encompasses both architectural planning and hands-on
                  development of applications <br />
                  <br />I live in Toronto, Canada
                </h3>

                <div className="absolute bottom-[80px]">
                  <a className="underline" href="#about-me">
                    about me
                  </a>
                  <a className="ml-5 underline" href="#try">
                    try chatgpt
                  </a>
                </div>
              </div>
            </section>

            {/* About me */}
            <section
              className="min-h-screen border-b border-line pt-[40px] pb-[80px]"
              id="about-me"
            >
              <div className="pr-[80px]">
                <h1 className="mb-8 text-left text-4xl font-semibold">
                  about me
                </h1>
                <div className="grid grid-cols-2 gap-[80px]">
                  <div>
                    <Highlight image={ladderImage} />
                    <div className="mb-[80px]" />
                    <Highlight image={computer} />
                  </div>
                  <div>
                    <Highlight image={dmb} />
                    <div className="mb-[80px]" />
                    <Highlight image={elizabethtown} />
                  </div>
                </div>
              </div>
            </section>

            {/* ChatGPT */}
            <section className="flex h-screen pt-[40px]" id="try">
              <div>
                <h1 className="text-left text-4xl font-semibold">
                  try chatgpt
                </h1>
              </div>
            </section>
          </div>

          {/* Right Panel */}
          <div className="absolute right-0 top-0 h-full w-[300px] overflow-hidden border-l border-line pt-[40px] pl-7 pr-7">
            <div className="absolute bottom-0 left-0 h-[500px] w-full bg-gradient-to-b from-transparent to-main"></div>
            {Array.from({ length: 50 }, (_, i) => (
              <Message />
            ))}
          </div>
        </div>

        {/* Footer */}
        <footer className="flex gap-[20px] p-[80px] font-thin">
          <span>
            <a href="mailto:prakash.raman.ka@gmail.com">
              prakash.raman.ka@gmail.com
            </a>{" "}
            / +1 (437) 261-0658
          </span>
        </footer>
      </main>
    </>
  );
};

export default Home;
